### PR TITLE
Remove "VC money" reference

### PR DESCRIPTION
**Pull request by vladh**
Sounds like Kagi does have VC money now? :P

### CODE REVIEW

**Comment by vprelovac** [comment]
We do not. Kagi raised money from its users, not VC fund.

**Comment by vladh** [comment]
@vprelovac Oh, that's cool — I guess the phrasing on the about page gave me the wrong impression:

> Kagi has raised $670K (...) thanks to 42 accredited investors

Perhaps others would also get that impression and it's worth rewording?

**Comment by vprelovac** [comment]
Yes should probably say

Kagi has raised $670K (...) from Kagi members if you want to change that

**Comment by vladh** [comment]
Hmm, I’ll let you guys word this the way you think is best. Reading the blog post, it looks like the investments were SAFE-based, and that only some, not all, investors are Kagi users. As a user, it’s not fully clear to me what the difference is between this and VC investment. Maybe more transparency here would make Kagi’s situation more understandable to users like me.

**Comment by vprelovac** [comment]
Sure, only one out of 42 was nto a kagi user at the time and is a personal friend - so they invsted because of me and were not using kagi at the time. and for that reason I could not say all of them but could have kept it simpler I guess.

**Pull request closed without merging**
