### PR TITLE
Remove misinformation

### PR DESCRIPTION
**Pull request by Coccocoahelper**
I know that it is not intentional, but Brave Goggles exist!

### CODE REVIEW

**Comment by vprelovac** [comment]
I've just tried and it is not clear to me how can I as a user can block a result after a search?

**Comment by Coccocoahelper** [comment]
> I've just tried and it is not clear to me how can I as a user can block a result after a search?

You can block a link with [Brave Goggles](https://search.brave.com/goggles/discover).

**Comment by vprelovac** [comment]
I did not find a way to remove a website from the search UI. Since this was the spirit of the line, perhaps change the line item to 'can block a website directly from search ui'?

**Comment by Coccocoahelper** [comment]
> I did not find a way to remove a website from the search UI. Since this was the spirit of the line, perhaps change the line item to 'can block a website directly from search ui'?

Good idea.

**Pull request merged**
