### PR TITLE
Docs reorg 2

### PR DESCRIPTION
**Pull request by gmgreg**
* Use consistent language for "Press Kit" across Kagi and Orion (replace "assets" with "Press Kit")
* Consolidate pages under "Support and Community"; add link to KagiHQ twitter

### CODE REVIEW

**Comment by vprelovac** [comment]
@gmgreg Note that assets are also developer assets for 3rd party apps

**Comment by gmgreg** [comment]
Looks like the developer "assets" are:

- download links to Orion
- download links for extensions to enable Kagi as default search for Safari (iOS/MacOS), Chrome, and Firefox
- Search URL (https://kagi.com/search?q={searchTerms})
- Autocomplete URL (https://kagi.com/api/autosuggest?q={searchTerms})

The rest (logo variants, mascot variants, fonts, colors, brand guidelines) are all press kit related just like the Orion press kit.  

Perhaps it would make sense to split these "assets" into 3.  A download page targeted at all users (since more than developers need these), a "press kit" page targeted at media, and a developer page targeted at developers.

Download page doesn't seem to exist anywhere.  Potentially add at kagi.com/downloads or in help.kagi.com -> company -> products
Press kit could remain as is but removing the "download" and "developer" items.
Developer items (search url and autocomplete url) could go in the documentation under "Developers" where API documentation currently is. 

Or we could revert to calling it "assets" though I'm not sure its obvious what is there until someone follows the link.

**Comment by gmgreg** [comment]
Just reverted that change (asset -> press kit) since that "fix" could be a bigger item.  Will deal with that in a separate PR.

**Comment by vprelovac** [comment]
@gmgreg Developers are using logo/mascot in 3rd party apps

**Comment by gmgreg** [comment]
@vprelovac I reverted the changes that impact "assets" and updated the PR.  The location of branding assets can be handled in a different PR.

Common practice is often to separate out the branding items for everyone who needs them (press, developers, etc.).  See https://openai.com/brand for an example.  Libraries and other developer specific downloads may be linked/hosted elsewhere, especially if partners might provide them.  Again see https://platform.openai.com/docs/libraries/python-library for an example.

**Comment by vprelovac** [comment]
No doubt, the difference is OpenAI has probably a person if not a team whose job is just this, we have me to do all this as devs are busy with other things. So is this the best use of my time?

**Comment by gmgreg** [comment]
Ok.  In the updated PR it's still called Assets and should have no impact on that area.

**Pull request merged**
